### ISSUE TITLE
Application will only scrape metrics on the first route

### ISSUE THREAD

**Issue by bilbof** [alphagov/cf_app_discovery#49]
Hello!

The [documentation](https://github.com/alphagov/cf_app_discovery#routes) mentions:

> This application will only scrape metrics on the first route, so other routes will be ignored.

I found this to be a bit of a gotcha, since we have two routes for an app, the first one is chosen and the second one is ignored. This is unfortunate since the metrics endpoint is only accessible to Prometheus via the my-hostname.cloudapps.digital route.

```
production                 my-service.service.gov.uk  /metrics  my-app re-ip-safelist-service
production   my-hostname   cloudapps.digital          /metrics  my-app re-ip-safelist-service
```

The fix was to delete and recreate the first route, so it becomes second in the routes list.

I wonder if cloudapps.digital routes could be preferred by the broker?

I am also confused why the cloudapps route is accessible to Prometheus. Would this be because the Prometheus requests to this host don't go through the `re-ip-safelist-service` route service we have set up if the host is cloudapps.digital?

Thanks!
Bill

**Comment by tlwr** [comment]
To answer your second question: the egress IP addresses of the production prometheis are allowed via the `re-ip-safelist-service`

**Comment by bilbof** [comment]
Ah thanks @tlwr, I think it'll be because we have CloudFront in front of the requests going through the service domain.
